#!/usr/bin/python

import sys
import fcntl

def ioctl_init(f):
	fcntl.ioctl(f, 0xff64)

def ioctl_uninit(f):
	fcntl.ioctl(f, 0xff65)

def ioctl_start(f):
	fcntl.ioctl(f, 0xff01)

def ioctl_sweep(f):
	fcntl.ioctl(f, 0xff02)

if __name__ == '__main__':
	# open livedump device file
	f = open('/dev/livedump')
	# execute subcommand
	subcmd = sys.argv[1]
	if 'init' == subcmd:
		ioctl_init(f)
	elif 'uninit' == subcmd:
		ioctl_uninit(f)
	elif 'start' == subcmd:
		ioctl_start(f)
	elif 'sweep' == subcmd:
		ioctl_sweep(f)
	# close livedump device file
	f.close
